Add new workflow
fraud-intelligence-limited/fil-documentation pull request #18
Opened 2023-04-20 13:19 UTC by safinsaf

2023-04-27 11:47 UTC, RamilMus approved these changes

2023-04-28 06:51 UTC, alexkg submitted a review, later dismissed

2023-05-02 02:35 UTC, 0x009922 commented on .github/workflows/vercel-deploy-dev.yaml
> +          node-version: '16'
```suggestion
          node-version: '18'
```

2023-05-02 02:35 UTC, 0x009922 commented on .github/workflows/vercel-deploy-dev.yaml
> +      - uses: actions/setup-node@v1
```suggestion
      - uses: actions/setup-node@v3
```

2023-05-02 07:47 UTC, 6r1d commented
LGTM generally, ping me for approval after applying the changes suggested by @0x009922.

2023-05-02 07:49 UTC, safinsaf commented on .github/workflows/vercel-deploy-dev.yaml
> +      - uses: actions/setup-node@v1
Done

2023-05-02 07:49 UTC, safinsaf commented on .github/workflows/vercel-deploy-dev.yaml
> +          node-version: '16'
Done

2023-05-02 07:52 UTC, 6r1d approved these changes
LGTM

2023-05-03 10:29 UTC, Cre-eD approved these changes

2023-05-03 13:55 UTC, wpi86 requested changes

2023-05-03 13:55 UTC, wpi86 commented on .github/workflows/vercel-deploy-dev.yaml
> +      - uses: actions/checkout@v2
please, pin version

2023-05-03 13:55 UTC, wpi86 commented on .github/workflows/vercel-deploy-dev.yaml
> +      - uses: actions/setup-node@v3
please, pin version

2023-05-04 16:50 UTC, safinsaf commented on .github/workflows/vercel-deploy-dev.yaml
> +      - uses: actions/checkout@v2
Done

2023-05-05 04:55 UTC, wpi86 approved these changes

2023-05-05 10:46 UTC, merged