FIB 1.3.1 Documentation Update
fraud-intelligence-limited/fil-documentation pull request #77
Opened 2024-09-09 12:50 UTC by yamkovoy

## TODO:
1. Add 2FA tutorial (probably within the **Registering an account** tutorial).
2. Update all Web App tutorials to reflect the UI and flow changes.
3. Update screenshots.
4. Verify that the new date format is used throughout the documentation (`YYYY-MM-DDTHH:MM:SS`)
5. Modify `config.ts`.

2024-09-09 13:29 UTC, Mingela commented on src/release-notes/index.md
> +### API Changes
I believe date-time format change should be reflected listing all calls affected, please check where we have date-time data among described API calls

2024-09-09 13:30 UTC, Mingela commented on src/release-notes/index.md
> +- Unified all of the time and date values to adhere to the single format: `YYYY-MM-DDTHH:MM:SS`
The previous comment relates to this

2024-09-09 13:31 UTC, Mingela commented on src/tutorials-api/retrieving-contributions.md
> +/api/v1/contribution-management/contribution?org=GA
```suggestion
/api/v1/contribution-management/contribution?dst=GA
```
?

2024-09-18 13:00 UTC, WRRicht3r requested changes

2024-09-18 13:00 UTC, WRRicht3r commented on src/release-notes/index.md
> +- Added the ability to select the destination countries when downloading fraud data via FIB Web App.
```suggestion
- Added the ability to select the destination countries when downloading fraud data via the FIB Web App.
```

2024-09-18 13:00 UTC, WRRicht3r commented on src/release-notes/index.md
> +- Added the ability to split the reward for uploaded contributions between the contributor and the original source of the fraud event data.
```suggestion
- Added the ability to split the reward for uploaded contributions between the contributor and the original fraud event data source.
```

2024-09-18 13:00 UTC, WRRicht3r commented on src/release-notes/index.md
> +  - Error messages are expanded with details and are more explicit now.
```suggestion
  - Error messages are expanded with details and are now more explicit.
```

2024-09-19 13:09 UTC, Mingela commented
Some more updates to mention:

Frontend (feel free to compare STAGE with DEV)
- Added date range selection shortcuts on download (today, last week, month etc)
- Eliminated inconsistencies in terminology
- Expanded info about selected filters on the download result screen (basically if some filters were kept default those were not shown)
- Added explicit errors in scenarios where those were missing before (e.g. instead of general 'Error' there should be an exact cause now)
- Deletions of the entries when reviewing your 'to upload' list are now revertible, smoother navigations and animations
- More clear behavior on changes for 'to flag' list

Backend
- sourcePeerId attribute must refer to a registered peer (or be omitted), otherwise an error is going to be returned
- Added email notification after successful password change

Please also accurately check all API endpoints, the date format changed everywhere

2024-09-27 03:56 UTC, DrLightman13 commented on src/overview/contributions.md
> +| `expiryDate` | `integer($int64)` | The exact time and date until which the event is considered relevant (represented as [Unix Epoch time](https://www.epochconverter.com/clock) in seconds). <br> By
expiryDate must comply with ISO 8601.

2024-09-27 03:57 UTC, DrLightman13 commented on src/overview/contributions.md
>  | `flagTimestamp` | `integer($int32)` | The exact time and date of when a contribution has been flagged. If a contribution hasn't been flagged at the time of observing, the field returns `null`. |
timestamp and flagTimestamp must comply with ISO 8601 as well.

2024-09-27 08:09 UTC, DrLightman13 commented on src/api-specification/contribution-controller/assembling-a-contribution.md
> +The `source` field is optional and is the same as the `sourcePeerId` value when [retrieving contributions](retrieving-contributions.md).
There have been some changes. 
1. The "source" has been renamed to "**sourcePeerId.**" Therefore, it is necessary to update this attribute in other parts of the document as well.
2. This part is no longer relevant: "The 'source' field is optional and is the same as the 'sourcePeerId'..."

2024-10-03 07:16 UTC, Mingela commented on .vitepress/config.mts
> +                  text: 'Toggling 2FA',
I remember we decided those were not needed, a client would use the web app for 2fa anyways

2024-10-03 07:16 UTC, Mingela commented on src/api-specification/contribution-controller/assembling-a-contribution.md
> +The value must be a valid FIB user, otherwise an error is returned.
```suggestion
The value for `sourcePeerId` must be a registered peer identifier, otherwise an error is returned.
```

2024-10-03 07:16 UTC, Mingela commented on src/img/s-upload.png
Please delete a couple of records on the screen so that the revertible deletion improvement is shown

2024-10-03 11:32 UTC, Mingela commented on src/api-specification/contribution-controller/retrieving-a-contribution-by-ID.md
> +Starting with FIB 1.3.1, expired contributions are no longer retrieved by ID.
```suggestion
Starting with version 1.3.1, expired contributions are no longer retrieved by ID.
```

2024-10-04 14:15 UTC, Mingela commented on src/api-specification/contribution-controller/retrieving-contributions.md
> +| `from` and `to` | `string` | The timeframe that the response entries are filtered by. Both are set as an exact time and date (ISO 8601: `YYYY-MM-DDTHH:MM:SSZ`). <br> If the `from` parameter is left
what about `to` being unspecified? in that case it'd search up to the latest record

2024-10-04 14:15 UTC, Mingela commented on src/api-specification/contribution-controller/retrieving-contributions.md
> +          assetDefinitionId: 'assetName#assetDomain',
```suggestion
          assetDefinitionId: 'string', // assetName#assetDomain
```

2024-10-04 14:15 UTC, Mingela commented on src/api-specification/contribution-controller/retrieving-contributions.md
> +          sourcePeerId: 'accountDomain'
```suggestion
          sourcePeerId: 'string' // accountDomain
```

2024-10-04 14:15 UTC, Mingela commented on src/overview/contributions.md
> +| `sourcePeerId` | `string` | The unique identifier of the original source that contributed the data. May be different from the `peerID`. <br> For details, see [Tokenomics: Reward split](./tokenomics
this should be added as an option attribute to the contribution assembling example/structure

2024-10-04 14:15 UTC, Mingela commented on src/overview/contributions.md
> +| `sourcePeerId` | `string` | The unique identifier of the original source that contributed the data. May be different from the `peerID`. <br> For details, see [Tokenomics: Reward split](./tokenomics
also I'd suggest expanding the description of the `Submitting contributions` with information about source peer id and that their balance would be increased based on the configured reward distribution (between uploader and source) ratio

2024-10-04 14:15 UTC, Mingela commented on src/tutorials-web/downloading-fraud-data.md
> +   - **Select fraud data** — select the fraud [type of the fraud events](../overview/fraud-events.md#types-of-fraud-events) that you wish to download.\
Select should be dropped on all entries, to be adjusted in the app; already done in Figma

2024-10-04 14:15 UTC, Mingela commented on src/tutorials-web/uploading-fraud-data.md
> +   `Fraud type`, `Fraud Identifier` (Number or range of numbers), `Origination country two-letter code` ([ISO 3166](https://www.iso.org/iso-3166-country-codes.html), Alpha-2), `Destination country tw
```suggestion
   `Fraud type`, `Fraud Identifier` (Number or range of numbers), `Origination country two-letter code` ([ISO 3166](https://www.iso.org/iso-3166-country-codes.html), Alpha-2), `Destination country two-letter code` ([ISO 3166](https://www.iso.org/iso-3166-country-codes.html), Alpha-2), `Original source of the data` (`peerId` of the peer)
```
not sure if 'peerId' got defined anywhere, we can drop that at all or just specify `peer identifier`

2024-10-10 12:36 UTC, Mingela commented on src/release-notes/index.md
> +  > [Overview > Contributions > Retrieving contributions](../overview/tokenomics.md#reward-split) — `expiryDate` description updated with details.
the link is wrong

cc @tonysani

2024-10-11 08:30 UTC, wongadre approved these changes
approved

2024-10-11 08:53 UTC, katenikiforova approved these changes

2024-10-11 10:34 UTC, Mingela commented
As for the split rule, please add wording around the fact the data records are available to both parties (uploader, owner) for free. I.e. considered theirs on upload.

2024-10-11 11:27 UTC, Mingela approved these changes

2024-10-16 12:34 UTC, Mingela commented on src/overview/contributions.md
> +| `assetDefinitionId` | `string` | The unique identifier of a contribution record on the blockchain network. |
it shouldn't be supplied, please remove

2024-10-16 12:34 UTC, Mingela commented on src/overview/contributions.md
> +| `sourcePeerId` | `string` | The unique identifier of the original source that contributed the data. May be different from the `peerID`. <br> For details, see [Tokenomics: Reward split](./tokenomics
Mark that optional please

2024-11-03 05:58 UTC, Mingela commented on src/release-notes/index.md
> +## Version 1.3.1 (YYYY-MM-DD)
```suggestion
## Version 1.3.1 (2024-11-06)
```

2024-11-06 04:57 UTC, Mingela approved these changes

2024-11-06 05:05 UTC, wongadre commented
approved

2024-11-06 05:09 UTC, baotn166 approved these changes

2024-11-06 05:09 UTC, merged